apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-tls
  namespace: authentik
spec:
  secretName: authentik-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: authentik.svc.cedille.club
  dnsNames:
    - authentik.svc.cedille.club
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-internal-tls
  namespace: authentik
spec:
  secretName: authentik-internal-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: authentik.svc.cedille.club
  dnsNames:
    - authentik.svc.cedille.club