apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-tls
  namespace: authentik
spec:
  secretName: authentik-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: authentik.svc.cedille.club
  dnsNames:
    - authentik.svc.cedille.club
  # Optional: Set the duration and renewal time
  duration: 2160h
  renewBefore: 360h
