apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: authentik
  namespace: authentik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  virtualhost:
    fqdn: authentik.svc.cedille.club
    tls:
      secretName: authentik-tls
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    requestHeadersPolicy:
      set:
        - name: X-Forwarded-For
          value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
        - name: Connection
          value: "Upgrade"
        - name: Upgrade
          value: "WebSocket"
        - name: X-Forwarded-Proto
          value: "https"
        - name: X-Forwarded-Host
          value: "%REQ(:AUTHORITY)%"
        - name: Host
          value: "%REQ(:AUTHORITY)%"
        - name: X-Scheme
          value: "https"
    cookieRewritePolicies:
      - name: authentik_session
        secure: true
        sameSite: "None"
    services:
    - name: authentik-server
      port: 80
      protocol: tls