apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: authentik
  namespace: authentik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  virtualhost:
    fqdn: authentik.svc.cedille.club
    tls:
      secretName: authentik-tls
      minimumProtocolVersion: "1.3"
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    requestHeadersPolicy:
      set:
        - name: X-Forwarded-For
          value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
        - name: X-Forwarded-Proto
          value: "%PROTOCOL%"
        # - name: X-Forwarded-Host
        #   value: "%HOST%"
        - name: Connection
          value: upgrade
        - name: Upgrade
          value: websocket
    services:
    - name: authentik-server
      port: 80