apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: authentik
  namespace: authentik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  virtualhost:
    fqdn: authentik.svc.cedille.club
    tls:
      secretName: authentik-tls
      minimumProtocolVersion: "1.3"
  routes:
  - conditions:
    - header:
        contains: application/grpc
        name: Content-Type
    - prefix: /ws
    enableWebsockets: true
    requestHeadersPolicy:
      set:

        - name: X-Forwarded-For
          value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
        - name: X-Real-IP
          value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
        - name: Host
          value: "authentik.svc.cedille.club"
        - name: Connection
          value: "upgrade"
        - name: Upgrade
          value: "websocket"
        - name: X-Forwarded-Proto
          value: "https"
    services:
    - name: authentik-server
      port: 80
      protocol: h2c
  - conditions:
    - prefix: /
    requestHeadersPolicy:
      set:
        - name: X-Forwarded-For
          value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
        - name: X-Real-IP
          value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
        # - name: Host
        #   value: "authentik.svc.cedille.club"
        - name: Connection
          value: "upgrade"
        - name: Upgrade
          value: "websocket"
        - name: X-Forwarded-Proto
          value: "https"
    services:
    - name: authentik-server
      port: 80