apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: collabora
  namespace: ocis
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  virtualhost:
    fqdn: collabora.svc.cedille.club
    tls:
      secretName: collabora-tls
      minimumProtocolVersion: "1.3"
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    requestHeadersPolicy:
      set:
        - name: X-Forwarded-For
          value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
        - name: X-Forwarded-Proto
          value: "%PROTOCOL%"
        - name: Upgrade
          value: websocket
    services:
    - name: collabora-online
      port: 9980
